<?php

namespace bundle\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RechercheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RechercheRepository extends EntityRepository
{
}
