<?php

namespace bundle\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getMailAndLogin()
    {
        $query = $this->createQueryBuilder('u')
            ->select('u.username, u.email')
            ->getQuery();

        return $query->getResult();
    }


    public function getUser($id)
    {
        $query = $this->createQueryBuilder('u')
            ->select('u.username, u.email, u.adresse, u.siteWeb, u.telephone')
            ->where('u.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $query->getResult();
    }
}
